-- ============================================================================
-- LendWise Mortgage System - Reference Data
-- Seed data for lookup tables and initial configuration
-- ============================================================================

-- Insert sample loan products
INSERT INTO LOAN_PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_TYPE, TERM_MONTHS, RATE_TYPE, MIN_LOAN_AMOUNT, MAX_LOAN_AMOUNT, MIN_LTV, MAX_LTV, MIN_FICO, MAX_DTI, OCCUPANCY_TYPES, PROPERTY_TYPES, IS_ACTIVE, EFFECTIVE_DATE) VALUES
('CONV-30-FIX', '30-Year Fixed Conventional', 'CONVENTIONAL', 360, 'FIXED', 50000, 766550, 3.00, 97.00, 620, 50.00, 'PRIMARY,SECONDARY,INVESTMENT', 'SINGLE_FAMILY,CONDO,TOWNHOUSE,MULTI_FAMILY', 'Y', DATE '2024-01-01');

INSERT INTO LOAN_PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_TYPE, TERM_MONTHS, RATE_TYPE, MIN_LOAN_AMOUNT, MAX_LOAN_AMOUNT, MIN_LTV, MAX_LTV, MIN_FICO, MAX_DTI, OCCUPANCY_TYPES, PROPERTY_TYPES, IS_ACTIVE, EFFECTIVE_DATE) VALUES
('CONV-15-FIX', '15-Year Fixed Conventional', 'CONVENTIONAL', 180, 'FIXED', 50000, 766550, 3.00, 97.00, 620, 50.00, 'PRIMARY,SECONDARY,INVESTMENT', 'SINGLE_FAMILY,CONDO,TOWNHOUSE', 'Y', DATE '2024-01-01');

INSERT INTO LOAN_PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_TYPE, TERM_MONTHS, RATE_TYPE, ARM_INDEX, ARM_MARGIN, ARM_CAPS, MIN_LOAN_AMOUNT, MAX_LOAN_AMOUNT, MIN_LTV, MAX_LTV, MIN_FICO, MAX_DTI, OCCUPANCY_TYPES, PROPERTY_TYPES, IS_ACTIVE, EFFECTIVE_DATE) VALUES
('CONV-5/1-ARM', '5/1 ARM Conventional', 'CONVENTIONAL', 360, 'ARM', 'SOFR', 2.75, '2/2/5', 50000, 766550, 5.00, 95.00, 640, 45.00, 'PRIMARY,SECONDARY', 'SINGLE_FAMILY,CONDO,TOWNHOUSE', 'Y', DATE '2024-01-01');

INSERT INTO LOAN_PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_TYPE, TERM_MONTHS, RATE_TYPE, MIN_LOAN_AMOUNT, MAX_LOAN_AMOUNT, MIN_LTV, MAX_LTV, MIN_FICO, MAX_DTI, OCCUPANCY_TYPES, PROPERTY_TYPES, IS_ACTIVE, EFFECTIVE_DATE) VALUES
('FHA-30-FIX', '30-Year Fixed FHA', 'FHA', 360, 'FIXED', 50000, 472030, 3.50, 96.50, 580, 56.90, 'PRIMARY', 'SINGLE_FAMILY,CONDO,TOWNHOUSE,MULTI_FAMILY', 'Y', DATE '2024-01-01');

INSERT INTO LOAN_PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_TYPE, TERM_MONTHS, RATE_TYPE, MIN_LOAN_AMOUNT, MAX_LOAN_AMOUNT, MIN_LTV, MAX_LTV, MIN_FICO, MAX_DTI, OCCUPANCY_TYPES, PROPERTY_TYPES, IS_ACTIVE, EFFECTIVE_DATE) VALUES
('VA-30-FIX', '30-Year Fixed VA', 'VA', 360, 'FIXED', 50000, 766550, 0.00, 100.00, 580, 60.00, 'PRIMARY', 'SINGLE_FAMILY,CONDO,TOWNHOUSE', 'Y', DATE '2024-01-01');

INSERT INTO LOAN_PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_TYPE, TERM_MONTHS, RATE_TYPE, MIN_LOAN_AMOUNT, MAX_LOAN_AMOUNT, MIN_LTV, MAX_LTV, MIN_FICO, MAX_DTI, OCCUPANCY_TYPES, PROPERTY_TYPES, IS_ACTIVE, EFFECTIVE_DATE) VALUES
('JUMBO-30-FIX', '30-Year Fixed Jumbo', 'JUMBO', 360, 'FIXED', 766551, 3000000, 10.00, 90.00, 700, 43.00, 'PRIMARY,SECONDARY', 'SINGLE_FAMILY,CONDO', 'Y', DATE '2024-01-01');

-- Insert sample base rates
INSERT INTO BASE_RATES (RATE_ID, PRODUCT_ID, EFFECTIVE_DATE, EXPIRATION_DATE, BASE_RATE, PAR_PRICE, LOCK_PERIOD_DAYS) VALUES
(1, 'CONV-30-FIX', DATE '2024-09-01', NULL, 0.0675, 100.0000, 30);
INSERT INTO BASE_RATES (RATE_ID, PRODUCT_ID, EFFECTIVE_DATE, EXPIRATION_DATE, BASE_RATE, PAR_PRICE, LOCK_PERIOD_DAYS) VALUES
(2, 'CONV-30-FIX', DATE '2024-09-01', NULL, 0.0650, 99.5000, 45);
INSERT INTO BASE_RATES (RATE_ID, PRODUCT_ID, EFFECTIVE_DATE, EXPIRATION_DATE, BASE_RATE, PAR_PRICE, LOCK_PERIOD_DAYS) VALUES
(3, 'CONV-30-FIX', DATE '2024-09-01', NULL, 0.0625, 99.0000, 60);
INSERT INTO BASE_RATES (RATE_ID, PRODUCT_ID, EFFECTIVE_DATE, EXPIRATION_DATE, BASE_RATE, PAR_PRICE, LOCK_PERIOD_DAYS) VALUES
(4, 'CONV-15-FIX', DATE '2024-09-01', NULL, 0.0599, 100.0000, 30);
INSERT INTO BASE_RATES (RATE_ID, PRODUCT_ID, EFFECTIVE_DATE, EXPIRATION_DATE, BASE_RATE, PAR_PRICE, LOCK_PERIOD_DAYS) VALUES
(5, 'FHA-30-FIX', DATE '2024-09-01', NULL, 0.0650, 100.0000, 30);
INSERT INTO BASE_RATES (RATE_ID, PRODUCT_ID, EFFECTIVE_DATE, EXPIRATION_DATE, BASE_RATE, PAR_PRICE, LOCK_PERIOD_DAYS) VALUES
(6, 'VA-30-FIX', DATE '2024-09-01', NULL, 0.0625, 100.0000, 30);
INSERT INTO BASE_RATES (RATE_ID, PRODUCT_ID, EFFECTIVE_DATE, EXPIRATION_DATE, BASE_RATE, PAR_PRICE, LOCK_PERIOD_DAYS) VALUES
(7, 'JUMBO-30-FIX', DATE '2024-09-01', NULL, 0.0725, 100.0000, 30);

COMMIT;

-- Verify data
SELECT 'LOAN_PRODUCTS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM LOAN_PRODUCTS
UNION ALL
SELECT 'BASE_RATES', COUNT(*) FROM BASE_RATES
UNION ALL
SELECT 'DOCUMENT_TYPES', COUNT(*) FROM DOCUMENT_TYPES
UNION ALL
SELECT 'COMPLIANCE_RULES', COUNT(*) FROM COMPLIANCE_RULES
UNION ALL
SELECT 'CONDITION_CODES', COUNT(*) FROM CONDITION_CODES
UNION ALL
SELECT 'LLPA_ADJUSTMENTS', COUNT(*) FROM LLPA_ADJUSTMENTS;
