-- ============================================================================
-- LendWise Mortgage System - Borrower Tables
-- Oracle Database Schema - Flow 1: Borrower Intake & Pre-Qualification
-- ============================================================================

-- Borrower master table
CREATE TABLE BORROWERS (
    BORROWER_ID         NUMBER PRIMARY KEY,
    SSN                 VARCHAR2(11) NOT NULL,
    FIRST_NAME          VARCHAR2(100) NOT NULL,
    LAST_NAME           VARCHAR2(100) NOT NULL,
    MIDDLE_NAME         VARCHAR2(100),
    DATE_OF_BIRTH       DATE,
    EMAIL               VARCHAR2(255),
    PHONE_PRIMARY       VARCHAR2(20),
    PHONE_SECONDARY     VARCHAR2(20),
    CITIZENSHIP_STATUS  VARCHAR2(50),
    MARITAL_STATUS      VARCHAR2(20),
    DEPENDENTS_COUNT    NUMBER(2) DEFAULT 0,
    CREATED_DATE        TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_DATE        TIMESTAMP,
    CREATED_BY          VARCHAR2(100),
    UPDATED_BY          VARCHAR2(100),
    CONSTRAINT UK_BORROWERS_SSN UNIQUE (SSN)
);

-- Borrower address table
CREATE TABLE BORROWER_ADDRESSES (
    ADDRESS_ID          NUMBER PRIMARY KEY,
    BORROWER_ID         NUMBER NOT NULL,
    ADDRESS_TYPE        VARCHAR2(20) NOT NULL,  -- CURRENT, PREVIOUS, MAILING
    STREET_ADDRESS      VARCHAR2(255) NOT NULL,
    UNIT_NUMBER         VARCHAR2(20),
    CITY                VARCHAR2(100) NOT NULL,
    STATE               VARCHAR2(2) NOT NULL,
    ZIP_CODE            VARCHAR2(10) NOT NULL,
    COUNTRY             VARCHAR2(50) DEFAULT 'USA',
    YEARS_AT_ADDRESS    NUMBER(4,2),
    MONTHS_AT_ADDRESS   NUMBER(3),
    HOUSING_TYPE        VARCHAR2(20),  -- OWN, RENT, OTHER
    MONTHLY_PAYMENT     NUMBER(12,2),
    EFFECTIVE_DATE      DATE,
    END_DATE            DATE,
    CREATED_DATE        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_ADDR_BORROWER FOREIGN KEY (BORROWER_ID)
        REFERENCES BORROWERS(BORROWER_ID)
);

-- Employment information
CREATE TABLE BORROWER_EMPLOYMENT (
    EMPLOYMENT_ID       NUMBER PRIMARY KEY,
    BORROWER_ID         NUMBER NOT NULL,
    EMPLOYER_NAME       VARCHAR2(200) NOT NULL,
    EMPLOYER_ADDRESS    VARCHAR2(500),
    EMPLOYER_PHONE      VARCHAR2(20),
    JOB_TITLE           VARCHAR2(100),
    EMPLOYMENT_TYPE     VARCHAR2(20),  -- FULL_TIME, PART_TIME, SELF_EMPLOYED, RETIRED
    START_DATE          DATE NOT NULL,
    END_DATE            DATE,
    IS_CURRENT          CHAR(1) DEFAULT 'Y',
    YEARS_IN_PROFESSION NUMBER(4,2),
    MONTHLY_INCOME      NUMBER(12,2) NOT NULL,
    BONUS_INCOME        NUMBER(12,2) DEFAULT 0,
    COMMISSION_INCOME   NUMBER(12,2) DEFAULT 0,
    OVERTIME_INCOME     NUMBER(12,2) DEFAULT 0,
    CREATED_DATE        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_EMP_BORROWER FOREIGN KEY (BORROWER_ID)
        REFERENCES BORROWERS(BORROWER_ID)
);

-- Assets
CREATE TABLE BORROWER_ASSETS (
    ASSET_ID            NUMBER PRIMARY KEY,
    BORROWER_ID         NUMBER NOT NULL,
    ASSET_TYPE          VARCHAR2(50) NOT NULL,  -- CHECKING, SAVINGS, RETIREMENT, STOCKS, REAL_ESTATE
    INSTITUTION_NAME    VARCHAR2(200),
    ACCOUNT_NUMBER      VARCHAR2(50),
    CURRENT_BALANCE     NUMBER(15,2) NOT NULL,
    VERIFICATION_STATUS VARCHAR2(20) DEFAULT 'PENDING',
    VERIFIED_DATE       DATE,
    CREATED_DATE        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_ASSET_BORROWER FOREIGN KEY (BORROWER_ID)
        REFERENCES BORROWERS(BORROWER_ID)
);

-- Liabilities
CREATE TABLE BORROWER_LIABILITIES (
    LIABILITY_ID        NUMBER PRIMARY KEY,
    BORROWER_ID         NUMBER NOT NULL,
    LIABILITY_TYPE      VARCHAR2(50) NOT NULL,  -- MORTGAGE, AUTO_LOAN, CREDIT_CARD, STUDENT_LOAN, OTHER
    CREDITOR_NAME       VARCHAR2(200),
    ACCOUNT_NUMBER      VARCHAR2(50),
    ORIGINAL_BALANCE    NUMBER(15,2),
    CURRENT_BALANCE     NUMBER(15,2) NOT NULL,
    MONTHLY_PAYMENT     NUMBER(12,2) NOT NULL,
    MONTHS_REMAINING    NUMBER(4),
    WILL_BE_PAID_OFF    CHAR(1) DEFAULT 'N',
    CREATED_DATE        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_LIAB_BORROWER FOREIGN KEY (BORROWER_ID)
        REFERENCES BORROWERS(BORROWER_ID)
);

-- Loan application table
CREATE TABLE LOAN_APPLICATIONS (
    LOAN_ID             NUMBER PRIMARY KEY,
    LOAN_NUMBER         VARCHAR2(20) NOT NULL,
    BORROWER_ID         NUMBER NOT NULL,
    CO_BORROWER_ID      NUMBER,
    LOAN_PURPOSE        VARCHAR2(20) NOT NULL,  -- PURCHASE, REFINANCE, CASH_OUT
    PROPERTY_TYPE       VARCHAR2(30),  -- SINGLE_FAMILY, CONDO, MULTI_FAMILY, TOWNHOUSE
    OCCUPANCY_TYPE      VARCHAR2(20),  -- PRIMARY, SECONDARY, INVESTMENT
    LOAN_AMOUNT         NUMBER(12,2) NOT NULL,
    DOWN_PAYMENT        NUMBER(12,2),
    PROPERTY_VALUE      NUMBER(12,2) NOT NULL,
    PROPERTY_ADDRESS    VARCHAR2(500),
    PROPERTY_CITY       VARCHAR2(100),
    PROPERTY_STATE      VARCHAR2(2),
    PROPERTY_ZIP        VARCHAR2(10),
    LOAN_TYPE           VARCHAR2(20),  -- CONVENTIONAL, FHA, VA, USDA, JUMBO
    LOAN_TERM           NUMBER(3),  -- 15, 20, 30 years
    INTEREST_RATE_TYPE  VARCHAR2(10),  -- FIXED, ARM
    DTI_RATIO           NUMBER(5,2),
    LTV_RATIO           NUMBER(5,2),
    CLTV_RATIO          NUMBER(5,2),
    PITI_RATIO          NUMBER(5,2),
    STATUS              VARCHAR2(50) DEFAULT 'INITIATED',
    STAGE               VARCHAR2(50) DEFAULT 'PRE_QUALIFICATION',
    LOAN_OFFICER_ID     VARCHAR2(50),
    PROCESSOR_ID        VARCHAR2(50),
    UNDERWRITER_ID      VARCHAR2(50),
    CREATED_DATE        TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_DATE        TIMESTAMP,
    SUBMITTED_DATE      TIMESTAMP,
    CONSTRAINT FK_LOAN_BORROWER FOREIGN KEY (BORROWER_ID)
        REFERENCES BORROWERS(BORROWER_ID),
    CONSTRAINT FK_LOAN_COBORROWER FOREIGN KEY (CO_BORROWER_ID)
        REFERENCES BORROWERS(BORROWER_ID),
    CONSTRAINT UK_LOAN_NUMBER UNIQUE (LOAN_NUMBER)
);

-- Loan estimates (LE)
CREATE TABLE LOAN_ESTIMATES (
    ESTIMATE_ID         NUMBER PRIMARY KEY,
    LOAN_ID             NUMBER NOT NULL,
    VERSION_NUMBER      NUMBER(3) DEFAULT 1,
    ESTIMATED_RATE      NUMBER(6,4),
    MONTHLY_PRINCIPAL_INTEREST NUMBER(12,2),
    MONTHLY_TAXES       NUMBER(12,2),
    MONTHLY_INSURANCE   NUMBER(12,2),
    MONTHLY_PMI         NUMBER(12,2),
    TOTAL_MONTHLY_PAYMENT NUMBER(12,2),
    ORIGINATION_CHARGES NUMBER(12,2),
    SERVICES_BORROWER_DID_NOT_SHOP NUMBER(12,2),
    SERVICES_BORROWER_DID_SHOP NUMBER(12,2),
    TOTAL_CLOSING_COSTS NUMBER(12,2),
    CASH_TO_CLOSE       NUMBER(12,2),
    ISSUE_DATE          DATE NOT NULL,
    EXPIRATION_DATE     DATE NOT NULL,
    ACCEPTED            CHAR(1) DEFAULT 'N',
    ACCEPTED_DATE       DATE,
    CREATED_DATE        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_LE_LOAN FOREIGN KEY (LOAN_ID)
        REFERENCES LOAN_APPLICATIONS(LOAN_ID)
);

-- Sequences
CREATE SEQUENCE SEQ_BORROWER_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ADDRESS_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EMPLOYMENT_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ASSET_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LIABILITY_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LOAN_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ESTIMATE_ID START WITH 1 INCREMENT BY 1;

-- Indexes
CREATE INDEX IDX_BORROWERS_SSN ON BORROWERS(SSN);
CREATE INDEX IDX_BORROWERS_NAME ON BORROWERS(LAST_NAME, FIRST_NAME);
CREATE INDEX IDX_LOAN_BORROWER ON LOAN_APPLICATIONS(BORROWER_ID);
CREATE INDEX IDX_LOAN_STATUS ON LOAN_APPLICATIONS(STATUS);
CREATE INDEX IDX_LOAN_STAGE ON LOAN_APPLICATIONS(STAGE);
CREATE INDEX IDX_LOAN_NUMBER ON LOAN_APPLICATIONS(LOAN_NUMBER);
