-- ============================================================================
-- LendWise Mortgage System - Underwriting Tables
-- Oracle Database Schema - Flow 3: Automated Underwriting System (AUS)
-- ============================================================================

-- Credit bureau response storage
CREATE TABLE CREDIT_BUREAU_RESPONSES (
    RESPONSE_ID         NUMBER PRIMARY KEY,
    BORROWER_ID         NUMBER NOT NULL,
    LOAN_ID             NUMBER NOT NULL,
    BUREAU_NAME         VARCHAR2(30) NOT NULL,  -- EXPERIAN, EQUIFAX, TRANSUNION
    REQUEST_DATE        TIMESTAMP NOT NULL,
    RESPONSE_DATE       TIMESTAMP,
    RAW_RESPONSE        CLOB,
    RESPONSE_FORMAT     VARCHAR2(20),  -- XML, JSON
    STATUS              VARCHAR2(20) DEFAULT 'PENDING',  -- PENDING, SUCCESS, ERROR
    ERROR_CODE          VARCHAR2(20),
    ERROR_MESSAGE       VARCHAR2(500),
    CONSTRAINT FK_CREDIT_BORROWER FOREIGN KEY (BORROWER_ID)
        REFERENCES BORROWERS(BORROWER_ID),
    CONSTRAINT FK_CREDIT_LOAN FOREIGN KEY (LOAN_ID)
        REFERENCES LOAN_APPLICATIONS(LOAN_ID)
);

-- Credit history (parsed from bureau responses)
CREATE TABLE CREDIT_HISTORY (
    CREDIT_ID           NUMBER PRIMARY KEY,
    BORROWER_ID         NUMBER NOT NULL,
    LOAN_ID             NUMBER NOT NULL,
    SSN                 VARCHAR2(11),
    FICO_SCORE          NUMBER(3),  -- Representative score used for decisioning
    EXPERIAN_SCORE      NUMBER(3),
    EQUIFAX_SCORE       NUMBER(3),
    TRANSUNION_SCORE    NUMBER(3),
    SCORE_MODEL         VARCHAR2(30),  -- FICO8, FICO9, VANTAGE
    PULL_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP,
    REPORT_DATE         DATE,
    TOTAL_ACCOUNTS      NUMBER(4),
    OPEN_ACCOUNTS       NUMBER(4),
    CLOSED_ACCOUNTS     NUMBER(4),
    DELINQUENT_ACCOUNTS NUMBER(4),
    DEROGATORIES        NUMBER(4),
    PUBLIC_RECORDS      NUMBER(4),
    INQUIRIES_LAST_6MO  NUMBER(3),
    OLDEST_ACCOUNT_DATE DATE,
    TOTAL_BALANCE       NUMBER(15,2),
    TOTAL_HIGH_CREDIT   NUMBER(15,2),
    REVOLVING_UTIL_PCT  NUMBER(5,2),
    CONSTRAINT FK_HIST_BORROWER FOREIGN KEY (BORROWER_ID)
        REFERENCES BORROWERS(BORROWER_ID),
    CONSTRAINT FK_HIST_LOAN FOREIGN KEY (LOAN_ID)
        REFERENCES LOAN_APPLICATIONS(LOAN_ID)
);

-- Credit tradelines (individual accounts from bureau)
CREATE TABLE CREDIT_TRADELINES (
    TRADELINE_ID        NUMBER PRIMARY KEY,
    CREDIT_ID           NUMBER NOT NULL,
    CREDITOR_NAME       VARCHAR2(200),
    ACCOUNT_NUMBER      VARCHAR2(30),
    ACCOUNT_TYPE        VARCHAR2(30),  -- REVOLVING, INSTALLMENT, MORTGAGE, AUTO
    ACCOUNT_STATUS      VARCHAR2(20),  -- OPEN, CLOSED, PAID, CHARGED_OFF
    OPEN_DATE           DATE,
    CLOSE_DATE          DATE,
    HIGH_CREDIT         NUMBER(12,2),
    CREDIT_LIMIT        NUMBER(12,2),
    CURRENT_BALANCE     NUMBER(12,2),
    MONTHLY_PAYMENT     NUMBER(12,2),
    PAYMENT_STATUS      VARCHAR2(10),  -- CURRENT, 30, 60, 90, 120, COLLECTION
    MONTHS_REVIEWED     NUMBER(3),
    LATE_30_COUNT       NUMBER(3),
    LATE_60_COUNT       NUMBER(3),
    LATE_90_COUNT       NUMBER(3),
    CONSTRAINT FK_TRADE_CREDIT FOREIGN KEY (CREDIT_ID)
        REFERENCES CREDIT_HISTORY(CREDIT_ID)
);

-- Underwriting decisions
CREATE TABLE UNDERWRITING_DECISIONS (
    DECISION_ID         NUMBER PRIMARY KEY,
    LOAN_ID             NUMBER NOT NULL,
    DECISION_TYPE       VARCHAR2(30) NOT NULL,  -- AUS_INITIAL, AUS_RESUBMIT, MANUAL
    DECISION_ENGINE     VARCHAR2(30),  -- DU, LP, INTERNAL
    DECISION_RESULT     VARCHAR2(20) NOT NULL,  -- APPROVE, ELIGIBLE, REFER, CAUTION, DECLINE
    DECISION_DATE       TIMESTAMP DEFAULT SYSTIMESTAMP,
    UNDERWRITER_ID      VARCHAR2(50),
    RISK_SCORE          NUMBER(5,2),
    RISK_GRADE          VARCHAR2(5),  -- A, B, C, D
    DTI_AT_DECISION     NUMBER(5,2),
    LTV_AT_DECISION     NUMBER(5,2),
    FICO_AT_DECISION    NUMBER(3),
    AUS_KEY_NUMBER      VARCHAR2(50),
    AUS_RESPONSE        CLOB,
    NOTES               VARCHAR2(2000),
    CONSTRAINT FK_DECISION_LOAN FOREIGN KEY (LOAN_ID)
        REFERENCES LOAN_APPLICATIONS(LOAN_ID)
);

-- Prior to Docs (PTD) and Prior to Funding (PTF) Conditions
CREATE TABLE LOAN_CONDITIONS (
    CONDITION_ID        NUMBER PRIMARY KEY,
    LOAN_ID             NUMBER NOT NULL,
    DECISION_ID         NUMBER,
    CONDITION_TYPE      VARCHAR2(10) NOT NULL,  -- PTD, PTF
    CONDITION_CODE      VARCHAR2(20) NOT NULL,
    CONDITION_CATEGORY  VARCHAR2(50),  -- CREDIT, INCOME, ASSET, PROPERTY, LEGAL
    CONDITION_DESC      VARCHAR2(500) NOT NULL,
    PRIORITY            VARCHAR2(10) DEFAULT 'NORMAL',  -- CRITICAL, HIGH, NORMAL, LOW
    STATUS              VARCHAR2(20) DEFAULT 'OPEN',  -- OPEN, SUBMITTED, CLEARED, WAIVED
    DUE_DATE            DATE,
    ASSIGNED_TO         VARCHAR2(100),
    DOCUMENT_ID         NUMBER,
    CLEARED_DATE        TIMESTAMP,
    CLEARED_BY          VARCHAR2(100),
    WAIVED_DATE         TIMESTAMP,
    WAIVED_BY           VARCHAR2(100),
    WAIVED_REASON       VARCHAR2(500),
    CREATED_DATE        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY          VARCHAR2(100),
    NOTES               VARCHAR2(1000),
    CONSTRAINT FK_COND_LOAN FOREIGN KEY (LOAN_ID)
        REFERENCES LOAN_APPLICATIONS(LOAN_ID),
    CONSTRAINT FK_COND_DECISION FOREIGN KEY (DECISION_ID)
        REFERENCES UNDERWRITING_DECISIONS(DECISION_ID),
    CONSTRAINT FK_COND_DOC FOREIGN KEY (DOCUMENT_ID)
        REFERENCES DOCUMENTS(DOCUMENT_ID)
);

-- Standard condition codes
CREATE TABLE CONDITION_CODES (
    CONDITION_CODE      VARCHAR2(20) PRIMARY KEY,
    CONDITION_TYPE      VARCHAR2(10) NOT NULL,
    CATEGORY            VARCHAR2(50),
    DESCRIPTION         VARCHAR2(500) NOT NULL,
    TYPICAL_RESOLUTION  VARCHAR2(500),
    IS_ACTIVE           CHAR(1) DEFAULT 'Y'
);

-- Insert standard PTD/PTF conditions
INSERT INTO CONDITION_CODES VALUES ('PTD001', 'PTD', 'INCOME', 'Verify current employment and income', 'Provide recent paystub dated within 30 days', 'Y');
INSERT INTO CONDITION_CODES VALUES ('PTD002', 'PTD', 'ASSET', 'Verify source of down payment funds', 'Provide bank statements showing 2-month history', 'Y');
INSERT INTO CONDITION_CODES VALUES ('PTD003', 'PTD', 'CREDIT', 'Explain credit inquiry', 'Provide letter of explanation for credit inquiry', 'Y');
INSERT INTO CONDITION_CODES VALUES ('PTD004', 'PTD', 'PROPERTY', 'Clear title issues', 'Obtain title update showing clear title', 'Y');
INSERT INTO CONDITION_CODES VALUES ('PTD005', 'PTD', 'INCOME', 'Verify self-employment income', 'Provide 2 years tax returns with Schedule C', 'Y');
INSERT INTO CONDITION_CODES VALUES ('PTF001', 'PTF', 'PROPERTY', 'Confirm homeowner insurance', 'Provide insurance binder with lender clause', 'Y');
INSERT INTO CONDITION_CODES VALUES ('PTF002', 'PTF', 'LEGAL', 'Execute closing documents', 'Sign all required closing documents', 'Y');
INSERT INTO CONDITION_CODES VALUES ('PTF003', 'PTF', 'ASSET', 'Verify funds to close', 'Provide proof of wire transfer', 'Y');
INSERT INTO CONDITION_CODES VALUES ('PTF004', 'PTF', 'PROPERTY', 'Final inspection satisfactory', 'Complete final inspection of property', 'Y');

-- Sequences
CREATE SEQUENCE SEQ_CREDIT_RESPONSE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CREDIT_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TRADELINE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DECISION_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CONDITION_ID START WITH 1 INCREMENT BY 1;

-- Indexes
CREATE INDEX IDX_CREDIT_RESP_LOAN ON CREDIT_BUREAU_RESPONSES(LOAN_ID);
CREATE INDEX IDX_CREDIT_HIST_LOAN ON CREDIT_HISTORY(LOAN_ID);
CREATE INDEX IDX_CREDIT_HIST_BORROWER ON CREDIT_HISTORY(BORROWER_ID);
CREATE INDEX IDX_TRADE_CREDIT ON CREDIT_TRADELINES(CREDIT_ID);
CREATE INDEX IDX_DECISION_LOAN ON UNDERWRITING_DECISIONS(LOAN_ID);
CREATE INDEX IDX_DECISION_RESULT ON UNDERWRITING_DECISIONS(DECISION_RESULT);
CREATE INDEX IDX_COND_LOAN ON LOAN_CONDITIONS(LOAN_ID);
CREATE INDEX IDX_COND_STATUS ON LOAN_CONDITIONS(STATUS);
CREATE INDEX IDX_COND_TYPE ON LOAN_CONDITIONS(CONDITION_TYPE);
