-- ============================================================================
-- LendWise Mortgage System - Compliance Tables
-- Oracle Database Schema - Flow 4: Loan Quality Analysis & Compliance Audit
-- ============================================================================

-- Compliance rule definitions
CREATE TABLE COMPLIANCE_RULES (
    RULE_ID             VARCHAR2(20) PRIMARY KEY,
    RULE_NAME           VARCHAR2(100) NOT NULL,
    RULE_CATEGORY       VARCHAR2(50) NOT NULL,  -- TRID, QM_ATR, HMDA, ECOA, RESPA
    RULE_TYPE           VARCHAR2(30),  -- TIMING, FEE_TOLERANCE, DTI_LIMIT, DISCLOSURE
    DESCRIPTION         VARCHAR2(1000),
    THRESHOLD_VALUE     NUMBER(10,4),
    THRESHOLD_TYPE      VARCHAR2(20),  -- PERCENT, DAYS, AMOUNT
    SEVERITY_IF_FAILED  VARCHAR2(20),  -- FATAL, MODERATE, LOW
    REGULATION_CITE     VARCHAR2(100),
    EFFECTIVE_DATE      DATE,
    EXPIRATION_DATE     DATE,
    IS_ACTIVE           CHAR(1) DEFAULT 'Y'
);

-- Insert standard compliance rules
INSERT INTO COMPLIANCE_RULES VALUES ('TRID001', 'LE Delivery Timing', 'TRID', 'TIMING', 'Loan Estimate must be delivered within 3 business days of application', 3, 'DAYS', 'FATAL', '12 CFR 1026.19(e)(1)(iii)', DATE '2015-10-03', NULL, 'Y');
INSERT INTO COMPLIANCE_RULES VALUES ('TRID002', 'CD Delivery Timing', 'TRID', 'TIMING', 'Closing Disclosure must be delivered at least 3 business days before closing', 3, 'DAYS', 'FATAL', '12 CFR 1026.19(f)(1)(ii)', DATE '2015-10-03', NULL, 'Y');
INSERT INTO COMPLIANCE_RULES VALUES ('TRID003', 'Zero Tolerance Fees', 'TRID', 'FEE_TOLERANCE', 'Zero tolerance fees cannot increase from LE to CD', 0, 'PERCENT', 'FATAL', '12 CFR 1026.19(e)(3)(i)', DATE '2015-10-03', NULL, 'Y');
INSERT INTO COMPLIANCE_RULES VALUES ('TRID004', '10% Tolerance Fees', 'TRID', 'FEE_TOLERANCE', '10% tolerance fees cannot increase more than 10% in aggregate', 10, 'PERCENT', 'MODERATE', '12 CFR 1026.19(e)(3)(ii)', DATE '2015-10-03', NULL, 'Y');
INSERT INTO COMPLIANCE_RULES VALUES ('QM001', 'DTI Cap', 'QM_ATR', 'DTI_LIMIT', 'Debt-to-Income ratio cannot exceed 43% for QM', 43, 'PERCENT', 'FATAL', '12 CFR 1026.43(e)(2)', DATE '2014-01-10', NULL, 'Y');
INSERT INTO COMPLIANCE_RULES VALUES ('QM002', 'Points and Fees Cap', 'QM_ATR', 'FEE_TOLERANCE', 'Points and fees cannot exceed 3% of loan amount (>$100K)', 3, 'PERCENT', 'FATAL', '12 CFR 1026.43(e)(3)', DATE '2014-01-10', NULL, 'Y');
INSERT INTO COMPLIANCE_RULES VALUES ('QM003', 'No Negative Amortization', 'QM_ATR', 'DISCLOSURE', 'Loan cannot have negative amortization features', NULL, NULL, 'FATAL', '12 CFR 1026.43(e)(2)', DATE '2014-01-10', NULL, 'Y');
INSERT INTO COMPLIANCE_RULES VALUES ('ATR001', 'Income Verification', 'QM_ATR', 'DISCLOSURE', 'Income must be verified using reliable third-party records', NULL, NULL, 'MODERATE', '12 CFR 1026.43(c)(4)', DATE '2014-01-10', NULL, 'Y');

-- Compliance audit log
CREATE TABLE COMPLIANCE_AUDIT_LOG (
    AUDIT_ID            NUMBER PRIMARY KEY,
    LOAN_ID             NUMBER NOT NULL,
    RULE_ID             VARCHAR2(20),
    AUDIT_TYPE          VARCHAR2(50) NOT NULL,  -- TRID_TIMING, FEE_TOLERANCE, QM_ATR, MANUAL
    AUDIT_SUBTYPE       VARCHAR2(50),
    AUDIT_RESULT        VARCHAR2(20) NOT NULL,  -- PASS, FAIL, WARNING, NOT_APPLICABLE
    AUDIT_SCORE         NUMBER(5,2),
    AUDIT_DETAILS       CLOB,
    FINDING_DESCRIPTION VARCHAR2(2000),
    ACTUAL_VALUE        VARCHAR2(100),
    EXPECTED_VALUE      VARCHAR2(100),
    VARIANCE            NUMBER(10,4),
    REMEDIATION_ACTION  VARCHAR2(1000),
    AUDIT_DATE          TIMESTAMP DEFAULT SYSTIMESTAMP,
    AUDITOR_ID          VARCHAR2(50),
    AUDITOR_TYPE        VARCHAR2(20),  -- SYSTEM, MANUAL, QC
    REVIEWED            CHAR(1) DEFAULT 'N',
    REVIEWED_BY         VARCHAR2(50),
    REVIEWED_DATE       TIMESTAMP,
    CONSTRAINT FK_AUDIT_LOAN FOREIGN KEY (LOAN_ID)
        REFERENCES LOAN_APPLICATIONS(LOAN_ID),
    CONSTRAINT FK_AUDIT_RULE FOREIGN KEY (RULE_ID)
        REFERENCES COMPLIANCE_RULES(RULE_ID)
);

-- Loan defects tracking
CREATE TABLE LOAN_DEFECTS (
    DEFECT_ID           NUMBER PRIMARY KEY,
    LOAN_ID             NUMBER NOT NULL,
    AUDIT_ID            NUMBER,
    DEFECT_CODE         VARCHAR2(20),
    DEFECT_CATEGORY     VARCHAR2(50) NOT NULL,  -- COMPLIANCE, CREDIT, INCOME, ASSET, PROPERTY, LEGAL
    DEFECT_SUBCATEGORY  VARCHAR2(50),
    SEVERITY            VARCHAR2(20) NOT NULL,  -- FATAL, MODERATE, LOW
    DESCRIPTION         VARCHAR2(1000) NOT NULL,
    IMPACT_ASSESSMENT   VARCHAR2(1000),
    ROOT_CAUSE          VARCHAR2(500),
    IDENTIFIED_BY       VARCHAR2(100),
    IDENTIFIED_DATE     TIMESTAMP DEFAULT SYSTIMESTAMP,
    STATUS              VARCHAR2(20) DEFAULT 'OPEN',  -- OPEN, IN_REMEDIATION, REMEDIATED, WAIVED, ESCALATED
    ASSIGNED_TO         VARCHAR2(100),
    DUE_DATE            DATE,
    REMEDIATION_PLAN    VARCHAR2(2000),
    REMEDIATION_ACTION  VARCHAR2(2000),
    REMEDIATED_DATE     TIMESTAMP,
    REMEDIATED_BY       VARCHAR2(100),
    WAIVED              CHAR(1) DEFAULT 'N',
    WAIVED_BY           VARCHAR2(100),
    WAIVED_DATE         TIMESTAMP,
    WAIVER_REASON       VARCHAR2(1000),
    WAIVER_APPROVAL     VARCHAR2(100),
    NOTES               CLOB,
    CONSTRAINT FK_DEFECT_LOAN FOREIGN KEY (LOAN_ID)
        REFERENCES LOAN_APPLICATIONS(LOAN_ID),
    CONSTRAINT FK_DEFECT_AUDIT FOREIGN KEY (AUDIT_ID)
        REFERENCES COMPLIANCE_AUDIT_LOG(AUDIT_ID)
);

-- TRID fee tracking (for tolerance calculations)
CREATE TABLE TRID_FEE_TRACKING (
    FEE_TRACK_ID        NUMBER PRIMARY KEY,
    LOAN_ID             NUMBER NOT NULL,
    DISCLOSURE_TYPE     VARCHAR2(10) NOT NULL,  -- LE, CD
    DISCLOSURE_VERSION  NUMBER(3),
    DISCLOSURE_DATE     DATE NOT NULL,
    FEE_CATEGORY        VARCHAR2(50) NOT NULL,  -- ORIGINATION, THIRD_PARTY_NOT_SHOP, THIRD_PARTY_SHOP
    FEE_NAME            VARCHAR2(100) NOT NULL,
    FEE_AMOUNT          NUMBER(12,2) NOT NULL,
    TOLERANCE_TYPE      VARCHAR2(20),  -- ZERO, TEN_PERCENT, NO_LIMIT
    CREATED_DATE        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_FEE_LOAN FOREIGN KEY (LOAN_ID)
        REFERENCES LOAN_APPLICATIONS(LOAN_ID)
);

-- Disclosure tracking
CREATE TABLE DISCLOSURE_TRACKING (
    DISCLOSURE_ID       NUMBER PRIMARY KEY,
    LOAN_ID             NUMBER NOT NULL,
    DISCLOSURE_TYPE     VARCHAR2(30) NOT NULL,  -- LOAN_ESTIMATE, CLOSING_DISCLOSURE, COC, OTHER
    VERSION_NUMBER      NUMBER(3) DEFAULT 1,
    ISSUE_DATE          DATE NOT NULL,
    DELIVERY_DATE       DATE,
    DELIVERY_METHOD     VARCHAR2(30),  -- MAIL, EMAIL, IN_PERSON, ESIGN
    RECEIVED_DATE       DATE,
    RECEIVED_METHOD     VARCHAR2(30),
    TRIGGER_REASON      VARCHAR2(100),  -- INITIAL, RATE_CHANGE, CLOSING_DATE_CHANGE, COC
    COC_REASON          VARCHAR2(500),
    IS_VALID            CHAR(1) DEFAULT 'Y',
    SUPERSEDED_BY       NUMBER,
    DOCUMENT_ID         NUMBER,
    CREATED_DATE        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY          VARCHAR2(100),
    CONSTRAINT FK_DISCL_LOAN FOREIGN KEY (LOAN_ID)
        REFERENCES LOAN_APPLICATIONS(LOAN_ID),
    CONSTRAINT FK_DISCL_SUPER FOREIGN KEY (SUPERSEDED_BY)
        REFERENCES DISCLOSURE_TRACKING(DISCLOSURE_ID),
    CONSTRAINT FK_DISCL_DOC FOREIGN KEY (DOCUMENT_ID)
        REFERENCES DOCUMENTS(DOCUMENT_ID)
);

-- Sequences
CREATE SEQUENCE SEQ_AUDIT_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DEFECT_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_FEE_TRACK_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DISCLOSURE_ID START WITH 1 INCREMENT BY 1;

-- Indexes
CREATE INDEX IDX_AUDIT_LOAN ON COMPLIANCE_AUDIT_LOG(LOAN_ID);
CREATE INDEX IDX_AUDIT_RESULT ON COMPLIANCE_AUDIT_LOG(AUDIT_RESULT);
CREATE INDEX IDX_AUDIT_DATE ON COMPLIANCE_AUDIT_LOG(AUDIT_DATE);
CREATE INDEX IDX_DEFECT_LOAN ON LOAN_DEFECTS(LOAN_ID);
CREATE INDEX IDX_DEFECT_SEVERITY ON LOAN_DEFECTS(SEVERITY);
CREATE INDEX IDX_DEFECT_STATUS ON LOAN_DEFECTS(STATUS);
CREATE INDEX IDX_FEE_LOAN ON TRID_FEE_TRACKING(LOAN_ID);
CREATE INDEX IDX_DISCL_LOAN ON DISCLOSURE_TRACKING(LOAN_ID);
CREATE INDEX IDX_DISCL_TYPE ON DISCLOSURE_TRACKING(DISCLOSURE_TYPE);
