-- ============================================================================
-- LendWise Mortgage System - Closing Tables
-- Oracle Database Schema - Flow 6: Closing Disclosure & E-Closing Pipeline
-- ============================================================================

-- Closing disclosure master
CREATE TABLE CLOSING_DISCLOSURES (
    CD_ID               NUMBER PRIMARY KEY,
    LOAN_ID             NUMBER NOT NULL,
    VERSION_NUMBER      NUMBER(3) DEFAULT 1,
    CD_DATE             DATE NOT NULL,
    CLOSING_DATE        DATE,
    DISBURSEMENT_DATE   DATE,
    SETTLEMENT_AGENT    VARCHAR2(200),
    SETTLEMENT_LOCATION VARCHAR2(500),
    STATUS              VARCHAR2(30) DEFAULT 'DRAFT',  -- DRAFT, ISSUED, SIGNED, FUNDED
    LOAN_AMOUNT         NUMBER(12,2) NOT NULL,
    INTEREST_RATE       NUMBER(6,4) NOT NULL,
    MONTHLY_PI          NUMBER(12,2),
    PREPAYMENT_PENALTY  CHAR(1) DEFAULT 'N',
    BALLOON_PAYMENT     CHAR(1) DEFAULT 'N',
    CREATED_DATE        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY          VARCHAR2(100),
    ISSUED_DATE         TIMESTAMP,
    ISSUED_BY           VARCHAR2(100),
    CONSTRAINT FK_CD_LOAN FOREIGN KEY (LOAN_ID)
        REFERENCES LOAN_APPLICATIONS(LOAN_ID)
);

-- Closing disclosure line items
CREATE TABLE CD_LINE_ITEMS (
    LINE_ITEM_ID        NUMBER PRIMARY KEY,
    CD_ID               NUMBER NOT NULL,
    SECTION             VARCHAR2(50) NOT NULL,  -- A_ORIGINATION, B_SERVICES_NOT_SHOP, C_SERVICES_SHOP, E_TAXES, F_PREPAIDS, G_ESCROW, H_OTHER
    LINE_NUMBER         VARCHAR2(10) NOT NULL,
    DESCRIPTION         VARCHAR2(200) NOT NULL,
    BORROWER_PAID_AT_CLOSE NUMBER(12,2) DEFAULT 0,
    BORROWER_PAID_BEFORE_CLOSE NUMBER(12,2) DEFAULT 0,
    SELLER_PAID_AT_CLOSE NUMBER(12,2) DEFAULT 0,
    SELLER_PAID_BEFORE_CLOSE NUMBER(12,2) DEFAULT 0,
    PAID_BY_OTHERS      NUMBER(12,2) DEFAULT 0,
    LE_AMOUNT           NUMBER(12,2),
    TOLERANCE_TYPE      VARCHAR2(20),  -- ZERO, TEN_PERCENT, NO_LIMIT
    VARIANCE            NUMBER(12,2),
    VARIANCE_REASON     VARCHAR2(500),
    CONSTRAINT FK_LINE_CD FOREIGN KEY (CD_ID)
        REFERENCES CLOSING_DISCLOSURES(CD_ID)
);

-- Cash to close summary
CREATE TABLE CD_CASH_TO_CLOSE (
    CTC_ID              NUMBER PRIMARY KEY,
    CD_ID               NUMBER NOT NULL,
    TOTAL_CLOSING_COSTS NUMBER(12,2),
    CLOSING_COSTS_PAID_BEFORE NUMBER(12,2),
    CLOSING_COSTS_FINANCED NUMBER(12,2),
    DOWN_PAYMENT        NUMBER(12,2),
    DEPOSIT             NUMBER(12,2),
    FUNDS_FOR_BORROWER  NUMBER(12,2),
    SELLER_CREDITS      NUMBER(12,2),
    ADJUSTMENTS         NUMBER(12,2),
    CASH_TO_CLOSE       NUMBER(12,2) NOT NULL,
    CASH_FROM_BORROWER  CHAR(1),  -- Y = to borrower, N = from borrower
    CONSTRAINT FK_CTC_CD FOREIGN KEY (CD_ID)
        REFERENCES CLOSING_DISCLOSURES(CD_ID)
);

-- Change of Circumstance (COC) tracking
CREATE TABLE CHANGE_OF_CIRCUMSTANCE (
    COC_ID              NUMBER PRIMARY KEY,
    LOAN_ID             NUMBER NOT NULL,
    COC_DATE            TIMESTAMP DEFAULT SYSTIMESTAMP,
    COC_TYPE            VARCHAR2(50) NOT NULL,  -- RATE_CHANGE, CLOSING_DATE, APR_CHANGE, BORROWER_REQUEST
    COC_REASON          VARCHAR2(500) NOT NULL,
    REQUIRES_REDISCLOSURE CHAR(1) DEFAULT 'Y',
    WAITING_PERIOD_WAIVED CHAR(1) DEFAULT 'N',
    WAIVER_REASON       VARCHAR2(500),
    PREVIOUS_CD_ID      NUMBER,
    NEW_CD_ID           NUMBER,
    CREATED_BY          VARCHAR2(100),
    APPROVED_BY         VARCHAR2(100),
    APPROVED_DATE       TIMESTAMP,
    NOTES               VARCHAR2(1000),
    CONSTRAINT FK_COC_LOAN FOREIGN KEY (LOAN_ID)
        REFERENCES LOAN_APPLICATIONS(LOAN_ID),
    CONSTRAINT FK_COC_PREV_CD FOREIGN KEY (PREVIOUS_CD_ID)
        REFERENCES CLOSING_DISCLOSURES(CD_ID),
    CONSTRAINT FK_COC_NEW_CD FOREIGN KEY (NEW_CD_ID)
        REFERENCES CLOSING_DISCLOSURES(CD_ID)
);

-- E-Sign sessions
CREATE TABLE ESIGN_SESSIONS (
    SESSION_ID          NUMBER PRIMARY KEY,
    LOAN_ID             NUMBER NOT NULL,
    CD_ID               NUMBER,
    SESSION_TYPE        VARCHAR2(30) NOT NULL,  -- INITIAL_DISCLOSURES, CLOSING_PACKAGE, AMENDMENT
    SESSION_STATUS      VARCHAR2(30) DEFAULT 'CREATED',  -- CREATED, SENT, VIEWED, PARTIALLY_SIGNED, COMPLETED, EXPIRED, CANCELLED
    VENDOR_SESSION_ID   VARCHAR2(100),  -- External e-sign vendor ID
    VENDOR_NAME         VARCHAR2(50),  -- DOCUSIGN, SNAPDOCS, etc.
    CREATED_DATE        TIMESTAMP DEFAULT SYSTIMESTAMP,
    SENT_DATE           TIMESTAMP,
    EXPIRATION_DATE     TIMESTAMP,
    COMPLETED_DATE      TIMESTAMP,
    CANCELLED_DATE      TIMESTAMP,
    CANCEL_REASON       VARCHAR2(500),
    CREATED_BY          VARCHAR2(100),
    CONSTRAINT FK_ESIGN_LOAN FOREIGN KEY (LOAN_ID)
        REFERENCES LOAN_APPLICATIONS(LOAN_ID),
    CONSTRAINT FK_ESIGN_CD FOREIGN KEY (CD_ID)
        REFERENCES CLOSING_DISCLOSURES(CD_ID)
);

-- E-Sign documents within a session
CREATE TABLE ESIGN_DOCUMENTS (
    ESIGN_DOC_ID        NUMBER PRIMARY KEY,
    SESSION_ID          NUMBER NOT NULL,
    DOCUMENT_NAME       VARCHAR2(200) NOT NULL,
    DOCUMENT_TYPE       VARCHAR2(50),
    PAGE_COUNT          NUMBER(4),
    VENDOR_DOC_ID       VARCHAR2(100),
    DOCUMENT_ID         NUMBER,  -- Link to our document storage
    STATUS              VARCHAR2(30) DEFAULT 'PENDING',  -- PENDING, SIGNED, DECLINED
    CONSTRAINT FK_ESIGNDOC_SESSION FOREIGN KEY (SESSION_ID)
        REFERENCES ESIGN_SESSIONS(SESSION_ID),
    CONSTRAINT FK_ESIGNDOC_DOC FOREIGN KEY (DOCUMENT_ID)
        REFERENCES DOCUMENTS(DOCUMENT_ID)
);

-- E-Sign signers
CREATE TABLE ESIGN_SIGNERS (
    SIGNER_ID           NUMBER PRIMARY KEY,
    SESSION_ID          NUMBER NOT NULL,
    SIGNER_TYPE         VARCHAR2(30) NOT NULL,  -- BORROWER, CO_BORROWER, SELLER, NOTARY, WITNESS
    SIGNER_NAME         VARCHAR2(200) NOT NULL,
    SIGNER_EMAIL        VARCHAR2(255) NOT NULL,
    SIGNER_PHONE        VARCHAR2(20),
    SIGNING_ORDER       NUMBER(2) DEFAULT 1,
    STATUS              VARCHAR2(30) DEFAULT 'PENDING',  -- PENDING, SENT, VIEWED, SIGNED, DECLINED
    SENT_DATE           TIMESTAMP,
    VIEWED_DATE         TIMESTAMP,
    SIGNED_DATE         TIMESTAMP,
    DECLINED_DATE       TIMESTAMP,
    DECLINE_REASON      VARCHAR2(500),
    IP_ADDRESS          VARCHAR2(50),
    CONSTRAINT FK_SIGNER_SESSION FOREIGN KEY (SESSION_ID)
        REFERENCES ESIGN_SESSIONS(SESSION_ID)
);

-- Funding records
CREATE TABLE FUNDING_RECORDS (
    FUNDING_ID          NUMBER PRIMARY KEY,
    LOAN_ID             NUMBER NOT NULL,
    CD_ID               NUMBER NOT NULL,
    FUNDING_DATE        DATE NOT NULL,
    FUNDING_STATUS      VARCHAR2(30) DEFAULT 'PENDING',  -- PENDING, FUNDED, SUSPENDED, CANCELLED
    WIRE_AMOUNT         NUMBER(12,2) NOT NULL,
    WIRE_REFERENCE      VARCHAR2(50),
    WIRE_DATE           DATE,
    WIRE_CONFIRMED      CHAR(1) DEFAULT 'N',
    RECORDING_DATE      DATE,
    RECORDING_NUMBER    VARCHAR2(50),
    FINAL_AUDIT_STATUS  VARCHAR2(20),  -- PASS, FAIL, SUSPENDED
    FINAL_AUDIT_DATE    TIMESTAMP,
    FINAL_AUDIT_BY      VARCHAR2(100),
    NOTES               VARCHAR2(1000),
    CREATED_DATE        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_FUND_LOAN FOREIGN KEY (LOAN_ID)
        REFERENCES LOAN_APPLICATIONS(LOAN_ID),
    CONSTRAINT FK_FUND_CD FOREIGN KEY (CD_ID)
        REFERENCES CLOSING_DISCLOSURES(CD_ID)
);

-- Funding conditions (final checks before wire)
CREATE TABLE FUNDING_CONDITIONS (
    FUND_COND_ID        NUMBER PRIMARY KEY,
    FUNDING_ID          NUMBER NOT NULL,
    CONDITION_TYPE      VARCHAR2(50) NOT NULL,  -- TITLE_CLEAR, INSURANCE_BOUND, DOCS_COMPLETE, WIRE_VERIFIED
    CONDITION_DESC      VARCHAR2(500),
    STATUS              VARCHAR2(20) DEFAULT 'PENDING',  -- PENDING, CLEARED, WAIVED
    CLEARED_DATE        TIMESTAMP,
    CLEARED_BY          VARCHAR2(100),
    NOTES               VARCHAR2(500),
    CONSTRAINT FK_FUNDCOND_FUND FOREIGN KEY (FUNDING_ID)
        REFERENCES FUNDING_RECORDS(FUNDING_ID)
);

-- Sequences
CREATE SEQUENCE SEQ_CD_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CD_LINE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CTC_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_COC_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ESIGN_SESSION_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ESIGN_DOC_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ESIGN_SIGNER_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_FUNDING_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_FUND_COND_ID START WITH 1 INCREMENT BY 1;

-- Indexes
CREATE INDEX IDX_CD_LOAN ON CLOSING_DISCLOSURES(LOAN_ID);
CREATE INDEX IDX_CD_STATUS ON CLOSING_DISCLOSURES(STATUS);
CREATE INDEX IDX_CD_LINE_CD ON CD_LINE_ITEMS(CD_ID);
CREATE INDEX IDX_COC_LOAN ON CHANGE_OF_CIRCUMSTANCE(LOAN_ID);
CREATE INDEX IDX_ESIGN_LOAN ON ESIGN_SESSIONS(LOAN_ID);
CREATE INDEX IDX_ESIGN_STATUS ON ESIGN_SESSIONS(SESSION_STATUS);
CREATE INDEX IDX_SIGNER_SESSION ON ESIGN_SIGNERS(SESSION_ID);
CREATE INDEX IDX_FUND_LOAN ON FUNDING_RECORDS(LOAN_ID);
CREATE INDEX IDX_FUND_STATUS ON FUNDING_RECORDS(FUNDING_STATUS);
