-- ============================================================================
-- LendWise Mortgage System - Loan Summary View
-- Provides a consolidated view of loan applications with key metrics
-- ============================================================================

CREATE OR REPLACE VIEW V_LOAN_SUMMARY AS
SELECT
    la.LOAN_ID,
    la.LOAN_NUMBER,
    b.BORROWER_ID,
    b.SSN AS BORROWER_SSN,
    b.FIRST_NAME || ' ' || b.LAST_NAME AS BORROWER_NAME,
    b.EMAIL AS BORROWER_EMAIL,
    cb.FIRST_NAME || ' ' || cb.LAST_NAME AS CO_BORROWER_NAME,
    la.LOAN_PURPOSE,
    la.PROPERTY_TYPE,
    la.OCCUPANCY_TYPE,
    la.LOAN_AMOUNT,
    la.PROPERTY_VALUE,
    la.DOWN_PAYMENT,
    la.LOAN_TYPE,
    la.LOAN_TERM,
    la.INTEREST_RATE_TYPE,
    la.DTI_RATIO,
    la.LTV_RATIO,
    la.CLTV_RATIO,
    la.STATUS AS LOAN_STATUS,
    la.STAGE AS LOAN_STAGE,
    la.LOAN_OFFICER_ID,
    la.PROCESSOR_ID,
    la.UNDERWRITER_ID,
    ch.FICO_SCORE AS REPRESENTATIVE_FICO,
    ud.DECISION_RESULT AS UNDERWRITING_DECISION,
    ud.DECISION_DATE AS UNDERWRITING_DATE,
    rl.LOCKED_RATE,
    rl.LOCK_EXPIRATION AS RATE_LOCK_EXPIRATION,
    rl.STATUS AS RATE_LOCK_STATUS,
    (SELECT COUNT(*) FROM LOAN_CONDITIONS lc
     WHERE lc.LOAN_ID = la.LOAN_ID AND lc.STATUS = 'OPEN') AS OPEN_CONDITIONS_COUNT,
    (SELECT COUNT(*) FROM LOAN_DEFECTS ld
     WHERE ld.LOAN_ID = la.LOAN_ID AND ld.STATUS = 'OPEN') AS OPEN_DEFECTS_COUNT,
    (SELECT COUNT(*) FROM DOCUMENTS d
     WHERE d.LOAN_ID = la.LOAN_ID) AS DOCUMENT_COUNT,
    la.CREATED_DATE AS APPLICATION_DATE,
    la.SUBMITTED_DATE,
    la.UPDATED_DATE AS LAST_UPDATED
FROM LOAN_APPLICATIONS la
JOIN BORROWERS b ON la.BORROWER_ID = b.BORROWER_ID
LEFT JOIN BORROWERS cb ON la.CO_BORROWER_ID = cb.BORROWER_ID
LEFT JOIN CREDIT_HISTORY ch ON la.LOAN_ID = ch.LOAN_ID
    AND ch.CREDIT_ID = (SELECT MAX(CREDIT_ID) FROM CREDIT_HISTORY WHERE LOAN_ID = la.LOAN_ID)
LEFT JOIN UNDERWRITING_DECISIONS ud ON la.LOAN_ID = ud.LOAN_ID
    AND ud.DECISION_ID = (SELECT MAX(DECISION_ID) FROM UNDERWRITING_DECISIONS WHERE LOAN_ID = la.LOAN_ID)
LEFT JOIN RATE_LOCKS rl ON la.LOAN_ID = rl.LOAN_ID
    AND rl.STATUS IN ('ACTIVE', 'EXTENDED')
ORDER BY la.CREATED_DATE DESC;

COMMENT ON TABLE V_LOAN_SUMMARY IS 'Consolidated view of loan applications with borrower, credit, underwriting, and rate lock information';
