-- ============================================================================
-- LendWise Mortgage System - Document Tables
-- Oracle Database Schema - Flow 2: Document Upload & Processing
-- ============================================================================

-- Document types reference table
CREATE TABLE DOCUMENT_TYPES (
    DOC_TYPE_CODE       VARCHAR2(30) PRIMARY KEY,
    DOC_TYPE_NAME       VARCHAR2(100) NOT NULL,
    CATEGORY            VARCHAR2(50),  -- INCOME, ASSET, IDENTITY, PROPERTY, OTHER
    IS_REQUIRED         CHAR(1) DEFAULT 'N',
    RETENTION_DAYS      NUMBER(4) DEFAULT 365,
    DESCRIPTION         VARCHAR2(500)
);

-- Insert standard document types
INSERT INTO DOCUMENT_TYPES (DOC_TYPE_CODE, DOC_TYPE_NAME, CATEGORY, IS_REQUIRED) VALUES
('PAYSTUB', 'Pay Stub', 'INCOME', 'Y');
INSERT INTO DOCUMENT_TYPES (DOC_TYPE_CODE, DOC_TYPE_NAME, CATEGORY, IS_REQUIRED) VALUES
('W2', 'W-2 Form', 'INCOME', 'Y');
INSERT INTO DOCUMENT_TYPES (DOC_TYPE_CODE, DOC_TYPE_NAME, CATEGORY, IS_REQUIRED) VALUES
('TAX_1040', 'Tax Return 1040', 'INCOME', 'Y');
INSERT INTO DOCUMENT_TYPES (DOC_TYPE_CODE, DOC_TYPE_NAME, CATEGORY, IS_REQUIRED) VALUES
('BANK_STMT', 'Bank Statement', 'ASSET', 'Y');
INSERT INTO DOCUMENT_TYPES (DOC_TYPE_CODE, DOC_TYPE_NAME, CATEGORY, IS_REQUIRED) VALUES
('RETIREMENT_STMT', 'Retirement Account Statement', 'ASSET', 'N');
INSERT INTO DOCUMENT_TYPES (DOC_TYPE_CODE, DOC_TYPE_NAME, CATEGORY, IS_REQUIRED) VALUES
('DRIVERS_LICENSE', 'Driver''s License', 'IDENTITY', 'Y');
INSERT INTO DOCUMENT_TYPES (DOC_TYPE_CODE, DOC_TYPE_NAME, CATEGORY, IS_REQUIRED) VALUES
('PASSPORT', 'Passport', 'IDENTITY', 'N');
INSERT INTO DOCUMENT_TYPES (DOC_TYPE_CODE, DOC_TYPE_NAME, CATEGORY, IS_REQUIRED) VALUES
('SSN_CARD', 'Social Security Card', 'IDENTITY', 'N');
INSERT INTO DOCUMENT_TYPES (DOC_TYPE_CODE, DOC_TYPE_NAME, CATEGORY, IS_REQUIRED) VALUES
('PURCHASE_CONTRACT', 'Purchase Contract', 'PROPERTY', 'Y');
INSERT INTO DOCUMENT_TYPES (DOC_TYPE_CODE, DOC_TYPE_NAME, CATEGORY, IS_REQUIRED) VALUES
('APPRAISAL', 'Appraisal Report', 'PROPERTY', 'Y');
INSERT INTO DOCUMENT_TYPES (DOC_TYPE_CODE, DOC_TYPE_NAME, CATEGORY, IS_REQUIRED) VALUES
('TITLE_REPORT', 'Title Report', 'PROPERTY', 'Y');
INSERT INTO DOCUMENT_TYPES (DOC_TYPE_CODE, DOC_TYPE_NAME, CATEGORY, IS_REQUIRED) VALUES
('INSURANCE_BINDER', 'Homeowner''s Insurance Binder', 'PROPERTY', 'Y');
INSERT INTO DOCUMENT_TYPES (DOC_TYPE_CODE, DOC_TYPE_NAME, CATEGORY, IS_REQUIRED) VALUES
('VOE', 'Verification of Employment', 'INCOME', 'N');
INSERT INTO DOCUMENT_TYPES (DOC_TYPE_CODE, DOC_TYPE_NAME, CATEGORY, IS_REQUIRED) VALUES
('VOD', 'Verification of Deposit', 'ASSET', 'N');
INSERT INTO DOCUMENT_TYPES (DOC_TYPE_CODE, DOC_TYPE_NAME, CATEGORY, IS_REQUIRED) VALUES
('OTHER', 'Other Document', 'OTHER', 'N');

-- Documents table
CREATE TABLE DOCUMENTS (
    DOCUMENT_ID         NUMBER PRIMARY KEY,
    LOAN_ID             NUMBER NOT NULL,
    BORROWER_ID         NUMBER,
    DOC_TYPE_CODE       VARCHAR2(30) NOT NULL,
    ORIGINAL_FILENAME   VARCHAR2(255) NOT NULL,
    STORED_FILENAME     VARCHAR2(255) NOT NULL,
    FILE_PATH           VARCHAR2(500) NOT NULL,
    FILE_SIZE           NUMBER(12),
    MIME_TYPE           VARCHAR2(100),
    CHECKSUM            VARCHAR2(64),
    UPLOAD_SOURCE       VARCHAR2(30),  -- WEB_UPLOAD, FTP, EMAIL, THIRD_PARTY
    UPLOAD_DATE         TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPLOADED_BY         VARCHAR2(100),
    STATUS              VARCHAR2(30) DEFAULT 'UPLOADED',
    CONSTRAINT FK_DOC_LOAN FOREIGN KEY (LOAN_ID)
        REFERENCES LOAN_APPLICATIONS(LOAN_ID),
    CONSTRAINT FK_DOC_BORROWER FOREIGN KEY (BORROWER_ID)
        REFERENCES BORROWERS(BORROWER_ID),
    CONSTRAINT FK_DOC_TYPE FOREIGN KEY (DOC_TYPE_CODE)
        REFERENCES DOCUMENT_TYPES(DOC_TYPE_CODE)
);

-- Document classification (AI/OCR results)
CREATE TABLE DOCUMENT_CLASSIFICATION (
    CLASSIFICATION_ID   NUMBER PRIMARY KEY,
    DOCUMENT_ID         NUMBER NOT NULL,
    CLASSIFIED_DOC_TYPE VARCHAR2(30),
    CONFIDENCE_SCORE    NUMBER(5,4),  -- 0.0000 to 1.0000
    CLASSIFICATION_METHOD VARCHAR2(30),  -- OCR, AI_MODEL, MANUAL
    CLASSIFIED_DATE     TIMESTAMP DEFAULT SYSTIMESTAMP,
    REVIEWED            CHAR(1) DEFAULT 'N',
    REVIEWED_BY         VARCHAR2(100),
    REVIEWED_DATE       TIMESTAMP,
    OVERRIDE_DOC_TYPE   VARCHAR2(30),
    CONSTRAINT FK_CLASS_DOC FOREIGN KEY (DOCUMENT_ID)
        REFERENCES DOCUMENTS(DOCUMENT_ID),
    CONSTRAINT FK_CLASS_OVERRIDE FOREIGN KEY (OVERRIDE_DOC_TYPE)
        REFERENCES DOCUMENT_TYPES(DOC_TYPE_CODE)
);

-- OCR extracted data
CREATE TABLE DOCUMENT_OCR_DATA (
    OCR_ID              NUMBER PRIMARY KEY,
    DOCUMENT_ID         NUMBER NOT NULL,
    EXTRACTED_TEXT      CLOB,
    OCR_ENGINE          VARCHAR2(50),
    OCR_VERSION         VARCHAR2(20),
    CONFIDENCE_SCORE    NUMBER(5,4),
    PROCESSING_TIME_MS  NUMBER(10),
    PROCESSED_DATE      TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_OCR_DOC FOREIGN KEY (DOCUMENT_ID)
        REFERENCES DOCUMENTS(DOCUMENT_ID)
);

-- OCR extracted fields (structured data)
CREATE TABLE DOCUMENT_EXTRACTED_FIELDS (
    FIELD_ID            NUMBER PRIMARY KEY,
    OCR_ID              NUMBER NOT NULL,
    FIELD_NAME          VARCHAR2(100) NOT NULL,
    FIELD_VALUE         VARCHAR2(1000),
    FIELD_TYPE          VARCHAR2(30),  -- STRING, NUMBER, DATE, CURRENCY
    CONFIDENCE_SCORE    NUMBER(5,4),
    PAGE_NUMBER         NUMBER(4),
    BOUNDING_BOX        VARCHAR2(100),  -- JSON coordinates
    CONSTRAINT FK_FIELD_OCR FOREIGN KEY (OCR_ID)
        REFERENCES DOCUMENT_OCR_DATA(OCR_ID)
);

-- Document validation results
CREATE TABLE DOCUMENT_VALIDATION (
    VALIDATION_ID       NUMBER PRIMARY KEY,
    DOCUMENT_ID         NUMBER NOT NULL,
    VALIDATION_TYPE     VARCHAR2(50) NOT NULL,  -- AUTHENTICITY, COMPLETENESS, CROSS_CHECK
    VALIDATION_RESULT   VARCHAR2(20) NOT NULL,  -- PASS, FAIL, WARNING
    VALIDATION_MESSAGE  VARCHAR2(1000),
    RELATED_DOCUMENT_ID NUMBER,
    VALIDATED_DATE      TIMESTAMP DEFAULT SYSTIMESTAMP,
    VALIDATED_BY        VARCHAR2(100),
    CONSTRAINT FK_VALID_DOC FOREIGN KEY (DOCUMENT_ID)
        REFERENCES DOCUMENTS(DOCUMENT_ID),
    CONSTRAINT FK_VALID_RELATED FOREIGN KEY (RELATED_DOCUMENT_ID)
        REFERENCES DOCUMENTS(DOCUMENT_ID)
);

-- Document checklist tracking
CREATE TABLE DOCUMENT_CHECKLIST (
    CHECKLIST_ID        NUMBER PRIMARY KEY,
    LOAN_ID             NUMBER NOT NULL,
    DOC_TYPE_CODE       VARCHAR2(30) NOT NULL,
    IS_REQUIRED         CHAR(1) DEFAULT 'Y',
    STATUS              VARCHAR2(20) DEFAULT 'PENDING',  -- PENDING, RECEIVED, VERIFIED, WAIVED
    DOCUMENT_ID         NUMBER,
    REQUESTED_DATE      DATE DEFAULT SYSDATE,
    RECEIVED_DATE       DATE,
    VERIFIED_DATE       DATE,
    WAIVED_DATE         DATE,
    WAIVED_BY           VARCHAR2(100),
    WAIVED_REASON       VARCHAR2(500),
    NOTES               VARCHAR2(1000),
    CONSTRAINT FK_CHECK_LOAN FOREIGN KEY (LOAN_ID)
        REFERENCES LOAN_APPLICATIONS(LOAN_ID),
    CONSTRAINT FK_CHECK_TYPE FOREIGN KEY (DOC_TYPE_CODE)
        REFERENCES DOCUMENT_TYPES(DOC_TYPE_CODE),
    CONSTRAINT FK_CHECK_DOC FOREIGN KEY (DOCUMENT_ID)
        REFERENCES DOCUMENTS(DOCUMENT_ID)
);

-- Sequences
CREATE SEQUENCE SEQ_DOCUMENT_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CLASSIFICATION_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_OCR_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_FIELD_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VALIDATION_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CHECKLIST_ID START WITH 1 INCREMENT BY 1;

-- Indexes
CREATE INDEX IDX_DOC_LOAN ON DOCUMENTS(LOAN_ID);
CREATE INDEX IDX_DOC_BORROWER ON DOCUMENTS(BORROWER_ID);
CREATE INDEX IDX_DOC_TYPE ON DOCUMENTS(DOC_TYPE_CODE);
CREATE INDEX IDX_DOC_STATUS ON DOCUMENTS(STATUS);
CREATE INDEX IDX_CLASS_DOC ON DOCUMENT_CLASSIFICATION(DOCUMENT_ID);
CREATE INDEX IDX_OCR_DOC ON DOCUMENT_OCR_DATA(DOCUMENT_ID);
CREATE INDEX IDX_CHECK_LOAN ON DOCUMENT_CHECKLIST(LOAN_ID);
CREATE INDEX IDX_CHECK_STATUS ON DOCUMENT_CHECKLIST(STATUS);
