-- ============================================================================
-- LendWise Mortgage System - Pricing Tables
-- Oracle Database Schema - Flow 5: Product Pricing Engine & Rate Lock
-- ============================================================================

-- Loan products reference table
CREATE TABLE LOAN_PRODUCTS (
    PRODUCT_ID          VARCHAR2(20) PRIMARY KEY,
    PRODUCT_NAME        VARCHAR2(100) NOT NULL,
    PRODUCT_TYPE        VARCHAR2(30) NOT NULL,  -- CONVENTIONAL, FHA, VA, USDA, JUMBO
    TERM_MONTHS         NUMBER(3) NOT NULL,  -- 180, 240, 360
    RATE_TYPE           VARCHAR2(10) NOT NULL,  -- FIXED, ARM
    ARM_INDEX           VARCHAR2(30),  -- SOFR, LIBOR
    ARM_MARGIN          NUMBER(6,4),
    ARM_CAPS            VARCHAR2(30),  -- 2/2/5, 5/2/5
    MIN_LOAN_AMOUNT     NUMBER(12,2),
    MAX_LOAN_AMOUNT     NUMBER(12,2),
    MIN_LTV             NUMBER(5,2),
    MAX_LTV             NUMBER(5,2),
    MIN_FICO            NUMBER(3),
    MAX_DTI             NUMBER(5,2),
    OCCUPANCY_TYPES     VARCHAR2(100),  -- PRIMARY,SECONDARY,INVESTMENT
    PROPERTY_TYPES      VARCHAR2(200),  -- SINGLE_FAMILY,CONDO,TOWNHOUSE
    IS_ACTIVE           CHAR(1) DEFAULT 'Y',
    EFFECTIVE_DATE      DATE,
    EXPIRATION_DATE     DATE
);

-- Base interest rates
CREATE TABLE BASE_RATES (
    RATE_ID             NUMBER PRIMARY KEY,
    PRODUCT_ID          VARCHAR2(20) NOT NULL,
    EFFECTIVE_DATE      DATE NOT NULL,
    EXPIRATION_DATE     DATE,
    BASE_RATE           NUMBER(6,4) NOT NULL,
    PAR_PRICE           NUMBER(8,4) DEFAULT 100.0000,
    LOCK_PERIOD_DAYS    NUMBER(3),
    CREATED_DATE        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY          VARCHAR2(100),
    CONSTRAINT FK_RATE_PRODUCT FOREIGN KEY (PRODUCT_ID)
        REFERENCES LOAN_PRODUCTS(PRODUCT_ID)
);

-- Loan Level Price Adjustments (LLPA)
CREATE TABLE LLPA_ADJUSTMENTS (
    LLPA_ID             NUMBER PRIMARY KEY,
    ADJUSTMENT_NAME     VARCHAR2(100) NOT NULL,
    ADJUSTMENT_TYPE     VARCHAR2(30) NOT NULL,  -- LTV, FICO, PROPERTY_TYPE, OCCUPANCY, STATE
    CRITERIA_MIN        NUMBER(10,4),
    CRITERIA_MAX        NUMBER(10,4),
    CRITERIA_VALUE      VARCHAR2(50),
    ADJUSTMENT_RATE     NUMBER(6,4) NOT NULL,  -- Basis points (negative = discount)
    ADJUSTMENT_PRICE    NUMBER(8,4),  -- Price adjustment
    PRODUCT_TYPES       VARCHAR2(200),  -- Comma-separated product types
    EFFECTIVE_DATE      DATE NOT NULL,
    EXPIRATION_DATE     DATE,
    IS_ACTIVE           CHAR(1) DEFAULT 'Y',
    NOTES               VARCHAR2(500)
);

-- Insert sample LLPA adjustments
INSERT INTO LLPA_ADJUSTMENTS VALUES (1, 'FICO 620-639 LTV >80', 'FICO', 620, 639, NULL, 3.000, -3.000, 'CONVENTIONAL', DATE '2024-01-01', NULL, 'Y', 'High LTV, low FICO adjustment');
INSERT INTO LLPA_ADJUSTMENTS VALUES (2, 'FICO 640-659 LTV >80', 'FICO', 640, 659, NULL, 2.750, -2.750, 'CONVENTIONAL', DATE '2024-01-01', NULL, 'Y', NULL);
INSERT INTO LLPA_ADJUSTMENTS VALUES (3, 'FICO 660-679 LTV >80', 'FICO', 660, 679, NULL, 2.250, -2.250, 'CONVENTIONAL', DATE '2024-01-01', NULL, 'Y', NULL);
INSERT INTO LLPA_ADJUSTMENTS VALUES (4, 'FICO 680-699 LTV >80', 'FICO', 680, 699, NULL, 1.500, -1.500, 'CONVENTIONAL', DATE '2024-01-01', NULL, 'Y', NULL);
INSERT INTO LLPA_ADJUSTMENTS VALUES (5, 'FICO 700-719 LTV >80', 'FICO', 700, 719, NULL, 1.000, -1.000, 'CONVENTIONAL', DATE '2024-01-01', NULL, 'Y', NULL);
INSERT INTO LLPA_ADJUSTMENTS VALUES (6, 'FICO >=720 LTV >80', 'FICO', 720, 850, NULL, 0.500, -0.500, 'CONVENTIONAL', DATE '2024-01-01', NULL, 'Y', NULL);
INSERT INTO LLPA_ADJUSTMENTS VALUES (7, 'Investment Property', 'OCCUPANCY', NULL, NULL, 'INVESTMENT', 1.750, -1.750, 'CONVENTIONAL', DATE '2024-01-01', NULL, 'Y', NULL);
INSERT INTO LLPA_ADJUSTMENTS VALUES (8, 'Second Home', 'OCCUPANCY', NULL, NULL, 'SECONDARY', 0.875, -0.875, 'CONVENTIONAL', DATE '2024-01-01', NULL, 'Y', NULL);
INSERT INTO LLPA_ADJUSTMENTS VALUES (9, 'Condo', 'PROPERTY_TYPE', NULL, NULL, 'CONDO', 0.750, -0.750, 'CONVENTIONAL', DATE '2024-01-01', NULL, 'Y', NULL);
INSERT INTO LLPA_ADJUSTMENTS VALUES (10, 'Cash-Out Refinance', 'PURPOSE', NULL, NULL, 'CASH_OUT', 1.250, -1.250, 'CONVENTIONAL', DATE '2024-01-01', NULL, 'Y', NULL);

-- Price quotes generated for borrowers
CREATE TABLE PRICING_QUOTES (
    QUOTE_ID            NUMBER PRIMARY KEY,
    LOAN_ID             NUMBER NOT NULL,
    PRODUCT_ID          VARCHAR2(20) NOT NULL,
    QUOTE_DATE          TIMESTAMP DEFAULT SYSTIMESTAMP,
    EXPIRATION_DATE     TIMESTAMP,
    BASE_RATE           NUMBER(6,4),
    ADJUSTED_RATE       NUMBER(6,4),
    TOTAL_LLPA          NUMBER(6,4),
    PRICE               NUMBER(8,4),
    DISCOUNT_POINTS     NUMBER(6,4),
    LENDER_CREDITS      NUMBER(12,2),
    APR                 NUMBER(6,4),
    MONTHLY_PI          NUMBER(12,2),
    TOTAL_MONTHLY       NUMBER(12,2),
    LOCK_PERIOD_DAYS    NUMBER(3),
    STATUS              VARCHAR2(20) DEFAULT 'ACTIVE',  -- ACTIVE, SELECTED, EXPIRED, LOCKED
    SELECTED            CHAR(1) DEFAULT 'N',
    SELECTED_DATE       TIMESTAMP,
    CONSTRAINT FK_QUOTE_LOAN FOREIGN KEY (LOAN_ID)
        REFERENCES LOAN_APPLICATIONS(LOAN_ID),
    CONSTRAINT FK_QUOTE_PRODUCT FOREIGN KEY (PRODUCT_ID)
        REFERENCES LOAN_PRODUCTS(PRODUCT_ID)
);

-- Quote LLPA breakdown
CREATE TABLE QUOTE_LLPA_DETAILS (
    DETAIL_ID           NUMBER PRIMARY KEY,
    QUOTE_ID            NUMBER NOT NULL,
    LLPA_ID             NUMBER NOT NULL,
    ADJUSTMENT_NAME     VARCHAR2(100),
    CRITERIA_MET        VARCHAR2(100),
    ADJUSTMENT_RATE     NUMBER(6,4),
    CONSTRAINT FK_DETAIL_QUOTE FOREIGN KEY (QUOTE_ID)
        REFERENCES PRICING_QUOTES(QUOTE_ID),
    CONSTRAINT FK_DETAIL_LLPA FOREIGN KEY (LLPA_ID)
        REFERENCES LLPA_ADJUSTMENTS(LLPA_ID)
);

-- Rate locks
CREATE TABLE RATE_LOCKS (
    LOCK_ID             NUMBER PRIMARY KEY,
    LOAN_ID             NUMBER NOT NULL,
    QUOTE_ID            NUMBER,
    LOCK_DATE           TIMESTAMP DEFAULT SYSTIMESTAMP,
    LOCK_EXPIRATION     DATE NOT NULL,
    LOCK_PERIOD_DAYS    NUMBER(3) NOT NULL,  -- 30, 45, 60
    LOCKED_RATE         NUMBER(6,4) NOT NULL,
    LOCKED_PRICE        NUMBER(8,4),
    LOCKED_POINTS       NUMBER(6,4),
    STATUS              VARCHAR2(20) DEFAULT 'ACTIVE',  -- ACTIVE, EXTENDED, EXPIRED, CANCELLED, FUNDED
    EXTENSION_COUNT     NUMBER(2) DEFAULT 0,
    EXTENDED_TO         DATE,
    EXTENSION_FEE       NUMBER(12,2) DEFAULT 0,
    CANCELLED_DATE      TIMESTAMP,
    CANCELLED_BY        VARCHAR2(100),
    CANCEL_REASON       VARCHAR2(500),
    LOCKED_BY           VARCHAR2(100),
    CONFIRMED           CHAR(1) DEFAULT 'N',
    CONFIRMED_DATE      TIMESTAMP,
    CONFIRMED_BY        VARCHAR2(100),
    NOTES               VARCHAR2(1000),
    CONSTRAINT FK_LOCK_LOAN FOREIGN KEY (LOAN_ID)
        REFERENCES LOAN_APPLICATIONS(LOAN_ID),
    CONSTRAINT FK_LOCK_QUOTE FOREIGN KEY (QUOTE_ID)
        REFERENCES PRICING_QUOTES(QUOTE_ID)
);

-- Rate lock history/audit
CREATE TABLE RATE_LOCK_HISTORY (
    HISTORY_ID          NUMBER PRIMARY KEY,
    LOCK_ID             NUMBER NOT NULL,
    ACTION_TYPE         VARCHAR2(30) NOT NULL,  -- CREATED, EXTENDED, CANCELLED, REPRICED, FUNDED
    ACTION_DATE         TIMESTAMP DEFAULT SYSTIMESTAMP,
    ACTION_BY           VARCHAR2(100),
    PREVIOUS_RATE       NUMBER(6,4),
    NEW_RATE            NUMBER(6,4),
    PREVIOUS_EXPIRATION DATE,
    NEW_EXPIRATION      DATE,
    NOTES               VARCHAR2(1000),
    CONSTRAINT FK_HIST_LOCK FOREIGN KEY (LOCK_ID)
        REFERENCES RATE_LOCKS(LOCK_ID)
);

-- Amortization schedules
CREATE TABLE AMORTIZATION_SCHEDULES (
    SCHEDULE_ID         NUMBER PRIMARY KEY,
    LOAN_ID             NUMBER NOT NULL,
    QUOTE_ID            NUMBER,
    GENERATED_DATE      TIMESTAMP DEFAULT SYSTIMESTAMP,
    LOAN_AMOUNT         NUMBER(12,2) NOT NULL,
    INTEREST_RATE       NUMBER(6,4) NOT NULL,
    TERM_MONTHS         NUMBER(3) NOT NULL,
    START_DATE          DATE NOT NULL,
    MONTHLY_PAYMENT     NUMBER(12,2) NOT NULL,
    TOTAL_INTEREST      NUMBER(15,2),
    TOTAL_PAYMENTS      NUMBER(15,2),
    CONSTRAINT FK_AMORT_LOAN FOREIGN KEY (LOAN_ID)
        REFERENCES LOAN_APPLICATIONS(LOAN_ID),
    CONSTRAINT FK_AMORT_QUOTE FOREIGN KEY (QUOTE_ID)
        REFERENCES PRICING_QUOTES(QUOTE_ID)
);

-- Amortization schedule details (monthly breakdown)
CREATE TABLE AMORTIZATION_DETAILS (
    DETAIL_ID           NUMBER PRIMARY KEY,
    SCHEDULE_ID         NUMBER NOT NULL,
    PAYMENT_NUMBER      NUMBER(4) NOT NULL,
    PAYMENT_DATE        DATE NOT NULL,
    BEGINNING_BALANCE   NUMBER(12,2) NOT NULL,
    PAYMENT_AMOUNT      NUMBER(12,2) NOT NULL,
    PRINCIPAL_AMOUNT    NUMBER(12,2) NOT NULL,
    INTEREST_AMOUNT     NUMBER(12,2) NOT NULL,
    ENDING_BALANCE      NUMBER(12,2) NOT NULL,
    CUMULATIVE_INTEREST NUMBER(15,2),
    CONSTRAINT FK_DET_SCHEDULE FOREIGN KEY (SCHEDULE_ID)
        REFERENCES AMORTIZATION_SCHEDULES(SCHEDULE_ID)
);

-- Sequences
CREATE SEQUENCE SEQ_RATE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LLPA_ID START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE SEQ_QUOTE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_QUOTE_DETAIL_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LOCK_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LOCK_HIST_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AMORT_SCHEDULE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AMORT_DETAIL_ID START WITH 1 INCREMENT BY 1;

-- Indexes
CREATE INDEX IDX_RATE_PRODUCT ON BASE_RATES(PRODUCT_ID);
CREATE INDEX IDX_RATE_DATE ON BASE_RATES(EFFECTIVE_DATE);
CREATE INDEX IDX_LLPA_TYPE ON LLPA_ADJUSTMENTS(ADJUSTMENT_TYPE);
CREATE INDEX IDX_QUOTE_LOAN ON PRICING_QUOTES(LOAN_ID);
CREATE INDEX IDX_LOCK_LOAN ON RATE_LOCKS(LOAN_ID);
CREATE INDEX IDX_LOCK_STATUS ON RATE_LOCKS(STATUS);
CREATE INDEX IDX_LOCK_EXP ON RATE_LOCKS(LOCK_EXPIRATION);
CREATE INDEX IDX_AMORT_LOAN ON AMORTIZATION_SCHEDULES(LOAN_ID);
